# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/write_to_BRAM_zed_cons.xdc

# Block Designs: bd/Write_to_BRAM/Write_to_BRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Write_to_BRAM || ORIG_REF_NAME==Write_to_BRAM} -quiet] -quiet

# IP: bd/Write_to_BRAM/ip/Write_to_BRAM_processing_system7_0_0/Write_to_BRAM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Write_to_BRAM_processing_system7_0_0 || ORIG_REF_NAME==Write_to_BRAM_processing_system7_0_0} -quiet] -quiet

# IP: bd/Write_to_BRAM/ip/Write_to_BRAM_axi_bram_ctrl_0_0/Write_to_BRAM_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Write_to_BRAM_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Write_to_BRAM_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Write_to_BRAM/ip/Write_to_BRAM_blk_mem_gen_0_0/Write_to_BRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Write_to_BRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==Write_to_BRAM_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Write_to_BRAM/ip/Write_to_BRAM_axi_smc_0/Write_to_BRAM_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Write_to_BRAM_axi_smc_0 || ORIG_REF_NAME==Write_to_BRAM_axi_smc_0} -quiet] -quiet

# IP: bd/Write_to_BRAM/ip/Write_to_BRAM_rst_ps7_0_50M_0/Write_to_BRAM_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Write_to_BRAM_rst_ps7_0_50M_0 || ORIG_REF_NAME==Write_to_BRAM_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Write_to_BRAM/ip/Write_to_BRAM_axi_bram_ctrl_0_1/Write_to_BRAM_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Write_to_BRAM_axi_bram_ctrl_0_1 || ORIG_REF_NAME==Write_to_BRAM_axi_bram_ctrl_0_1} -quiet] -quiet

# XDC: bd/Write_to_BRAM/Write_to_BRAM_ooc.xdc
